// ══════════════════════════════════════════════════════════════
// CPU End-to-End Verification Testbench
//
// Tests the full flow:
// Assembly → Python Assembler → cpu_test.hex → $readmemh → Execution
//
// This verifies only the CPU logic (Hazards, Forwarding, Branches).
// ══════════════════════════════════════════════════════════════
module tb_cpu_e2e;

    reg clk;
    reg reset;
    
    // Instantiate Top Pipeline
    top uut(
        .clk(clk),
        .reset(reset)
    );
    
    integer pass_count;
    integer fail_count;
    
    // ── Simulation Control ────────────────────────────────
    initial begin
        clk = 0;
        reset = 1;
        pass_count = 0;
        fail_count = 0;
        
        #10;
        reset = 0;
        
        // Load the hex file generated by the Python Assembler
        // We load it here AFTER the reset so that the memory's internal
        // reset logic (which zeroes the array) doesn't overwrite it.
        #5;
        $readmemh("assembler/cpu_test.hex", uut.Inst_Memory.I_Mem);
        
        $display("==================================================");
        $display(" Starting End-to-End CPU Execution...");
        $display("==================================================");
        
        // Run for 60 cycles. The assembly program takes ~40 cycles.
        repeat(60) @(posedge clk);
        
        // ── Final Automated Verification ─────────────────────
        $display("\n==================================================");
        $display(" FINAL VERIFICATION CHECKS");
        $display("==================================================");
        check(uut.Reg_File.Registers[1],  32'd10, "x1  == 10");
        check(uut.Reg_File.Registers[2],  32'd20, "x2  == 20");
        check(uut.Reg_File.Registers[3],  32'd30, "x3  == 30");
        check(uut.Reg_File.Registers[4],  32'd20, "x4  == 20");
        check(uut.Reg_File.Registers[5],  32'd20, "x5  == 20");
        check(uut.Reg_File.Registers[6],  32'd30, "x6  == 30");
        check(uut.Reg_File.Registers[7],  32'd30, "x7  == 30");
        check(uut.Reg_File.Registers[8],  32'd40, "x8  == 40");
        check(uut.Reg_File.Registers[9],  32'd0,  "x9  == 0");
        check(uut.Reg_File.Registers[10], 32'd30, "x10 == 30");
        
        // Memory check (using byte address divided by 4 for word array index)
        // Memory 4 maps to D_Memory[4] in this word-addressed scheme
        check(uut.Data_mem.D_Memory[4], 32'd30, "Mem[4] == 30");
        
        $display("==================================================");
        $display(" Results: %0d PASS, %0d FAIL", pass_count, fail_count);
        $display("==================================================");
        $stop;
    end
    
    // ── Debug Monitoring ──────────────────────────────────
    always @(posedge clk) begin
        if (!reset) begin
            // 1. Fetch Stage
            $display("[%0t ns] PC: %0d | Fetch: %h", $time, uut.PC_IF, uut.instruction_IF);
            
            // 2. Branch Resolution (MEM Stage)
            if (uut.PCSrc_MEM) begin
                $display("    >>> BRANCH TAKEN! Flushing pipeline, jumping to PC: %0d", uut.BranchTarget_MEM);
            end
            
            // 3. Memory Writes (MEM Stage)
            // Ensure we aren't accidentally triggering the NPU addresses (256+)
            if (uut.MemWrite_MEM && (uut.ALU_result_MEM < 8'd256)) begin
                $display("    >>> MEM WRITE: Mem[%0d] = %0d", uut.ALU_result_MEM, uut.RD2_MEM);
            end
            
            // 4. Register Writes (WB Stage)
            if (uut.RegWrite_WB && uut.RD_WB != 0) begin
                $display("    >>> REG WRITE: x%0d = %0d", uut.RD_WB, uut.WriteBack_WB);
            end
        end
    end
    
    // ── Check Task ─────────────────────────────────────────
    task check;
        input [31:0] actual;
        input [31:0] expected;
        input [63:0] label;
        begin
            if (actual === expected) begin
                $display(" PASS | %-12s | got %0d", label, actual);
                pass_count = pass_count + 1;
            end
            else begin
                $display(" FAIL | %-12s | expected %0d, got %0d", label, expected, actual);
                fail_count = fail_count + 1;
            end
        end
    endtask
    
    // ── Clock Generation ───────────────────────────────────
    always begin
        #5 clk = ~clk;
    end

endmodule
