// ══════════════════════════════════════════════════════════════
// NPU End-to-End Verification Testbench
//
// Tests the full flow:
// Assembly → Python Assembler → npu_test.hex → $readmemh → Execution
//
// This verifies the CPU pipeline's ability to communicate with
// the memory-mapped NPU, trigger computation, poll, and read back.
// ══════════════════════════════════════════════════════════════
module tb_npu_e2e;

    reg clk;
    reg reset;
    
    // Instantiate Top Pipeline
    top uut(
        .clk(clk),
        .reset(reset)
    );
    
    integer pass_count;
    integer fail_count;
    
    // ── Simulation Control ────────────────────────────────
    initial begin
        clk = 0;
        reset = 1;
        pass_count = 0;
        fail_count = 0;
        
        #10;
        reset = 0;
        
        // Load the hex file generated by the Python Assembler
        #5;
        $readmemh("assembler/npu_test.hex", uut.Inst_Memory.I_Mem);
        
        $display("==================================================");
        $display(" Starting End-to-End NPU Execution...");
        $display("==================================================");
        
        // Run for 120 cycles. The assembly program involves a poll loop
        // and a 10-cycle NPU compute, so we need extra cycles.
        repeat(120) @(posedge clk);
        
        // ── Final Automated Verification ─────────────────────
        $display("\n==================================================");
        $display(" FINAL VERIFICATION CHECKS");
        $display("==================================================");
        check(uut.Reg_File.Registers[1],  32'd2,  "A[0][0] setup (x1 == 2)");
        check(uut.Reg_File.Registers[2],  32'd4,  "A[0][1] setup (x2 == 4)");
        check(uut.Reg_File.Registers[3],  32'd3,  "B[0][0] setup (x3 == 3)");
        check(uut.Reg_File.Registers[4],  32'd5,  "B[1][0] setup (x4 == 5)");
        check(uut.Reg_File.Registers[5],  32'd1,  "Start bit     (x5 == 1)");
        check(uut.Reg_File.Registers[6],  32'd1,  "Done flag     (x6 == 1)");
        check(uut.Reg_File.Registers[7],  32'd26, "Math Result   (x7 == 26)");
        
        $display("==================================================");
        $display(" Results: %0d PASS, %0d FAIL", pass_count, fail_count);
        $display("==================================================");
        $stop;
    end
    
    // ── Debug Monitoring ──────────────────────────────────
    always @(posedge clk) begin
        if (!reset) begin
            // 1. Branch Resolution (MEM Stage)
            if (uut.PCSrc_MEM) begin
                $display("[%0t ns] BRANCH TAKEN! Flushing pipeline, jumping to PC: %0d", $time, uut.BranchTarget_MEM);
            end
            
            // 2. Memory Writes (MEM Stage)
            if (uut.MemWrite_MEM) begin
                if (uut.ALU_result_MEM >= 8'd256) begin
                    $display("[%0t ns] >>> NPU WRITE: Addr[%0d] = %0d", $time, uut.ALU_result_MEM, uut.RD2_MEM);
                end else begin
                    $display("[%0t ns] >>> MEM WRITE: Mem[%0d]  = %0d", $time, uut.ALU_result_MEM, uut.RD2_MEM);
                end
            end
            
            // 3. Register Writes (WB Stage)
            // To reduce spam from the polling loop, only print when x6 changes or x7 is written
            if (uut.RegWrite_WB && uut.RD_WB != 0) begin
                if (uut.RD_WB == 6 && uut.WriteBack_WB == 1) begin
                    $display("[%0t ns] >>> REG WRITE: x6 (Done flag) changed to 1!", $time);
                end else if (uut.RD_WB != 6) begin
                    $display("[%0t ns] >>> REG WRITE: x%0d = %0d", $time, uut.RD_WB, uut.WriteBack_WB);
                end
            end
        end
    end
    
    // ── Check Task ─────────────────────────────────────────
    task check;
        input [31:0] actual;
        input [31:0] expected;
        input [63:0] label;
        begin
            if (actual === expected) begin
                $display(" PASS | %-25s | got %0d", label, actual);
                pass_count = pass_count + 1;
            end
            else begin
                $display(" FAIL | %-25s | expected %0d, got %0d", label, expected, actual);
                fail_count = fail_count + 1;
            end
        end
    endtask
    
    // ── Clock Generation ───────────────────────────────────
    always begin
        #5 clk = ~clk;
    end

endmodule
